@main def m(args: String*) =
  val words = List("the", "quick", "brown", "fox")
  val numbers = List(1, 2, 3, -4, 5)
  println(s"map: ${words.map(_.length)}")
  println(s"flatMap: ${words.flatMap(_.toList)}")
  println(s"range: ${List.range(1, 5)}")
  println(s" <- foreach: ${words.foreach(word => print(word))}")
  println(s"filter: ${words.filter(_.length == 3)}")
  println(s"partition: ${words.partition(_.length == 3)}")
  println(s"find: ${words.find(_.length == 5)}")
  println(s"takeWhile: ${numbers.takeWhile(_ > 0)}")
  println(s"dropWhile: ${words.dropWhile(_.startsWith("t"))}")
  println(s"span: ${numbers.span(_ > 0)}")
  println(s"exists: ${numbers.exists(_ > 0)}")
  println(s"forall: ${words.forall(_.length < 4)}")
